### ISSUE TITLE
'text' attribute causing issues

### ISSUE THREAD

**Issue by Paquette-Xavier** [acgd-webdev-1/stylish-beets#1]
I've finished my css code and everything is working fine except for the text attribute that is a part of the code that google gave me when I chose the fonts. 

I didn't change that code at all, as I figured it would work fine, but now it is my only issue and I'm not sure how to fix it with what Markbot is telling me. 

<img width="1050" alt="screen shot 2016-02-04 at 3 45 29 pm" src="https://cloud.githubusercontent.com/assets/16688062/12829158/a217f510-cb56-11e5-845c-0adf287907b1.png">
<img width="510" alt="screen shot 2016-02-04 at 3 45 46 pm" src="https://cloud.githubusercontent.com/assets/16688062/12829161/a66717cc-cb56-11e5-9ef6-9960e9ab468f.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
Yeah, Google's code isn't good. Go ahead and delete the `type="text/css"` part from that line.

**Comment by Paquette-Xavier** [comment]
Great! That worked, thanks!
